apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-app-1

  labels:

    app: nginx-app-1

spec:

  replicas: 3

  selector:

    matchLabels:

      app: nginx-app-1

  template:

    metadata:

      labels:

        app: nginx-app-1

    spec:

      containers:

      - name: nginx

        image: nginx:latest

        ports:

        - containerPort: 80

---


apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  type: ClusterIP # Optional field (default)
  clusterIP: 10.10.0.1 # within service cluster ip range
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080