apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:

  name: my-app-1

  namespace: argocd

  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:

  destination:

    namespace: default

    server: https://kubernetes.default.svc

  project: default

  source:

    path: child-apps/app-1

    repoURL: https://github.com/AmosZh/gics-proc.git

    targetRevision: HEAD