apiVersion: argoproj.io/v1alpha1
kind: application
metadata:
  name: my-app-1
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: child-apps/app-1
    repoURL: https://github.com/AmosZh/gics-proc.git
    targetRevision: HEAD