apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: amir-example-app1
        hostPrefix: amir
      - namespace: amir-example-app2
        hostPrefix: amir
      - namespace: amir-example-app3
        hostPrefix: amir
      - namespace: amir-example-app4
        hostPrefix: amir
      - namespace: amir-example-app5
        hostPrefix: amir
      - namespace: amir-example-app6
        hostPrefix: amir
      - namespace: amir-example-app7
        hostPrefix: amir
      - namespace: amir-example-app8
        hostPrefix: amir
      - namespace: amir-example-app9
        hostPrefix: amir
      - namespace: amir-example-app10
        hostPrefix: amir
      - namespace: amir-example-app11
        hostPrefix: amir
      - namespace: amir-example-app12
        hostPrefix: amir
  template:
    metadata:
      name: '{{namespace}}'
      namespace: argocd
      labels:
        argocd.argoproj.io/instance: gics-proc
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/AmosZh/gics-proc.git
        targetRevision: HEAD
        path: argocd/helm/
      #   helm:
      #     parameters:
      #     - name: 'ingress.host'
      #       value: '{{hostPrefix}}.rke2-cluster-test.atix-training.de'
      #     - name: 'image.tag'
      #       value: "$ARGOCD_APP_REVISION"
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
          - "CreateNamespace=true"



# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: gics-app4
#   namespace: argocd
# spec:
#   generators:
#   - list:
#       elements:
#       - namespace: gics-app4-first-deployment
#   template:
#     metadata:
#       name: '{{namespace}}'
#       namespace: argocd
#       labels:
#         argocd.argoproj.io/instance: gics-proc
#       finalizers:
#       - resources-finalizer.argocd.argoproj.io
#     spec:
#       project: default
#       source:
#         repoURL: 
#         targetRevision: HEAD
#         path: 
#       destination:
#         name: in-cluster
#         namespace: '{{namespace}}'
#       syncPolicy:
#         automated:
#           prune: true
#           allowEmpty: true
#         syncOptions:
#           - "CreateNamespace=true"
